version: "3.7"

services:
  docker-redis:
    image: redis:7.0.5-alpine
    container_name: docker-redis
    ports:
      - 6379:6379
    volumes:
      - docker-redis-data:/var/lib/redis

volumes:
  docker-redis-data:
