version: "3.7"

services:
  docker-db:
    image: amd64/mysql:8.0.31
    platform: linux/amd64
    container_name: docker-db
    restart: always
    ports:
      - 3306:3306
    environment: # 환경변수
      - MYSQL_USER=docker
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_DATABASE=docker
    command: # 명령어1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - docker-db-data:/var/lib/mysql

volumes:
  docker-db-data:
